### ISSUE TITLE
Authorisation example using Cognito User Pools?

### ISSUE THREAD

**Issue by v79** [cjkent/osiris#504]
I'm looking for an example of authorisation using Cognito user pools, but none is available in the Wiki. I've added my arn to `authConfig = AuthConfig.CognitoUserPools(...)` and wrapped my function in `auth(CognitoUserPoolsAuth) {		get("/helloplain") {... } {}` but when I test it using the AWS Cognito HostedUI I always get a `{"message":"Missing Authentication Token"}` response. I'm sure I've missed something but cannot work out what...

Many thanks.

**Comment by cjkent** [comment]
Hi,

I have good news and bad news.

Bad news: I always intended to turn my Cognito test code into an example project but never got round to it. So there's nothing available right now.

Good news: I'm working on a project at the moment and I'm intending to use Cognito. So I should have some working code in the next few days and I'll create an example project from that.

**Comment by cjkent** [comment]
I've got a very basic example working that uses the Cognito CLI to create a user, verify the user and request a token. And the uses `curl` to make a request using the token.

See [here](https://stackoverflow.com/questions/49063292/how-to-generate-access-token-for-an-aws-cognito-user) for more details about the CLI part.

The main complication is setting up a user pool, app client and user in Cognito. You've already done everything you need to in Osiris.

I'll add a more comprehensive example to `osiris-examples` when I have some working code.

This assumes you already have a user pool set up. 

# Create the user

```shell script
aws cognito-idp sign-up --region {your-region} --client-id {your-client-id} --username {your-username} --password {your-password}
```
The client ID is an "App client id" from the "App clients" section of the user pool console. 

# Verify the User

```shell script
aws cognito-idp admin-confirm-sign-up --region {your-region} --user-pool-id {your-user-pool-id} --username {your-user-name}
```

# Request a token

```shell script
aws cognito-idp admin-initiate-auth --region {your-aws-region} --cli-input-json file://auth.json
```

Where `auth.json` is

```json
{
    "UserPoolId": "{your-user-pool-id}",
    "ClientId": "{your-client-id}",
    "AuthFlow": "ADMIN_NO_SRP_AUTH",
    "AuthParameters": {
        "USERNAME": "{your-username}",
        "PASSWORD": "{your-password}"
    }
}
```

The response will look something like this

```json
{
    "AuthenticationResult": {
        "ExpiresIn": 3600,
        "IdToken": "{your-id-token}",
        "RefreshToken": "{your-refresh-token}",
        "TokenType": "Bearer",
        "AccessToken": "{your-access-token}"
    },
    "ChallengeParameters": {}
}
```

# Make a Request

You need to use the `IdToken` from the response for the `Authorization` header with a prefix of `Bearer`:

```shell script
curl -H "Authorization: Bearer {your-id-token}" https://{your-api-id}.execute-api.{your-aws-region}.amazonaws.com/dev/helloplain
```
Let me know if you get it working, or if you have any more questions.

Cheers,
Chris

**Comment by v79** [comment]
Thank you, I now have that working via `curl`, and works directly or via my API Gateway. I just need to understand why the AWS HostedUI isn't sending the same authentication headers.

**Comment by cjkent** [comment]
I've got an example working with the hosted UI. It's in `osiris-examples/cognito` on a branch called `cognito`. I haven't merged it yet because it still has some rough edges, but you can take a look at it if you want a preview.

The most interesting parts are
* `root.template` - creating the user pool, user pool client and user pool domain
* `index.html` - redirecting to the login page and using the token after a successful login

Things to note:
* There is an error in the hosted UI after signing up with a new user (with absolutly no error message). Which means you have to go into the Cognito console to confirm the user. If you figure out a way to stop this happening please let me know.
* You have to edit the variables at the top of the `onLoad` function in `index.html` with the details of your account, region, Cognito client ID and API ID. I hope to automate this before I merge the example

After deploying the example, enter this in the terminal to open a brower pointing at your API
```
mvn osiris:open -f core -Dstage=dev -Dendpoint=/
```
The page should detect that you're not logged in and redirect you to Cognito to register or log in. Sign up, confirm the new uesr in the Cognito console, and then visit the page again. This time you can sign in with the new user and you should be redirected back to `index.html`.

The script in the page will take the ID token from the URL hash and use it when you make a request to the API by pressing the button.

**Comment by cjkent** [comment]
I've published the Cognito example [here](https://github.com/cjkent/osiris-examples/tree/master/cognito).

You still need to manually the HTML with details of your AWS account and deployed project IDs. I figured it was more important to have a working Cognito example than to keep polishing it endlessly.
